version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - './:/app'
    ports:
      - 5000:5000
    command: "uvicorn app.main:app  --host 0.0.0.0  --reload --port 5000  --log-level debug"
    networks:
      - app-network

networks:
  app-network:
    external:
      name: external-emails
